### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by czyczyczy** [open-mmlab/mmsr#10]
when i read the **LQGT_dataset.py**, i found that
`        if self.opt['color']:  # change color space if necessary`
           ` img_GT = util.channel_convert(img_GT.shape[2], self.opt['color'], [img_GT])[0]`
the **_img_GT.shape[2]_** is **3**  
the **_self.opt['color']_** is **RGB** in **train_SRResNet.yml**  
but the **def channel_convert** in _util.py_  
`    if in_c == 3 and tar_type == 'gray':  # BGR to gray`
        ` gray_list = [cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in img_list]`
        `return [np.expand_dims(img, axis=2) for img in gray_list]`
    `elif in_c == 3 and tar_type == 'y':  # BGR to y`
       ` y_list = [bgr2ycbcr(img, only_y=True) for img in img_list]`
       ` return [np.expand_dims(img, axis=2) for img in y_list]`
   ` elif in_c == 1 and tar_type == 'RGB':  # gray/y to BGR`
        `return [cv2.cvtColor(img, cv2.COLOR_GRAY2BGR) for img in img_list]`
    `else:`
        `return img_list`  

has no  **_in_c=3 and tar_type == 'RGB'_**,so it just **_return img_list_**。
Is the means when i use DIV2K, i don't need to deal with the conversion among BGR, gray and y?

**Comment by xinntao** [comment]
Yes, if you want to train on RGB channels and you use the DIV2K, then no conversion is needed.
The conversion is executed when you have RGB images, but you want to training on gray images.

**Comment by czyczyczy** [comment]
> Yes, if you want to train on RGB channels and you use the DIV2K, then no conversion is needed.
> The conversion is executed when you have RGB images, but you want to train on gray images.

Thank you very much for your answer .
