### ISSUE TITLE
About the training setting

### ISSUE THREAD

**Issue by czyczyczy** [open-mmlab/mmsr#12]
I use the DIV2K800 as my datasets. I am confused about the setting of `niter、T_period、restarts` with the `batch_size=16`, if i want to change the batch_size such as 32、64... , how to set these parameter  `niter、T_period、restarts、learning_rate`?

**Comment by xinntao** [comment]
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
You can find a more user-friendly codebase in MMEdting
