### ISSUE TITLE
CPU Inferences Possible?

### ISSUE THREAD

**Issue by athenawisdoms** [open-mmlab/mmsr#13]
1. Is it possible to use CPU (without GPU) for performing inferences on images using the pre-trained model? Such as for SRGAN?

2. Also, does `mmsr` work with the [SRGAN model](https://modelzoo.co/model/srgan) that is tagged with Tensorflow not pyTorch?

Thank you!

**Comment by zhangcl** [comment]
For the first question, the answer is yes. I've tried and verified it on ESRGAN. There are 3 things you need to do.
1. In your inference option file (e.g. test_ESRGAN.yml), remove the line containing "gpu_ids: [0]"
2. In codes/options/options.py, remove the following lines in function "def parse(opt_path, is_train_True)"
`
    gpu_list = ','.join(str(x) for x in opt['gpu_ids'])
`
`
    os.environ['CUDA_VISIBLE_DEVICES'] = gpu_list
`
`
    print('export CUDA_VISIBLE_DEVICES=' + gpu_list)
`
3. In codes/models/SRGAN_model.py, remove the following lines inside function "def __init__(self, opt):"
`
    if opt['dist']:
`
`
      self.netG = DistributedDataParallel(self.netG, device_ids=[torch.cuda.current_device()])
`
`
    else:
`
`
        self.netG = DataParallel(self.netG)
`

But remember, running on CPU is very slow.

**Comment by EnJiang** [comment]
@zhangcl Hi, thanks for your reply. But how can I compile DCN without GPUs?(See "Dependencies and Installation" in the README, Deformable Convolution). Or you build this project on a machine with GPUs and migrate it to a machine without GPU?

**Comment by zhangcl** [comment]
@EnJiang  Yes, I use a computer with GPU on it.

To compile DCN, you don't need to have a GPU. All you need is the nvcc compiler, whch is included in CUDA. So installing CUDA should fix your problem.

**Comment by zhangcl** [comment]
@EnJiang  I did try it today without GPU. It failed. The error is as follows: 

> RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at

In that case, you will have to have a GPU in your system.

**Comment by EnJiang** [comment]
@zhangcl I agree.
This is how I did it on tencent cloud:
1. Start a GPU VM instance with a NVIDIA V100 GPU.
2. Compile DCN and make sure relative code can run on GPU.
3. Change the code accordingly as @zhangcl  suggested. Make sure the code runs on CPU only (nvidia-smi to make sure the process is not using GPU)
4. Make an Image/Snapshot of this VM.
5. Start a CPU machine with the mentioned Image/Snapshot.

But I do get a memory leak problem. That is, the more samples I run the more memory the model uses and finally I get a OOM error.
I wonder can you guys reproduce it?
