### ISSUE TITLE
URL in Wiki/Model Zoo/TOF Results does not work

### ISSUE THREAD

**Issue by BumjunPark** [open-mmlab/mmsr#14]
Hello,

Thank you for sharing helpful data.

However, URL to download TOF results does not work.

Could you please fix it?

Thank you.

**Comment by xinntao** [comment]
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
