### ISSUE TITLE
Discriminator models missing in model-zoo

### ISSUE THREAD

**Issue by maartenvds** [open-mmlab/mmsr#15]
Hi,

Thanks for this wonderful repo, it's really useful in my current research.

I want to fine-tune SRGAN on a custom dataset using pre-trained weights. However, only the weights for the generators are available in the model-zoo. I was wondering if you could provide the discriminator weights as well?

Thanks in advance

**Comment by vegetable09** [comment]
+1

**Comment by xinntao** [comment]
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
We will add a discriminator in the MMEditing.
