### ISSUE TITLE
How do we use this program?

### ISSUE THREAD

**Issue by bparker06** [open-mmlab/mmsr#16]
On the "Training and Testing" wiki page it says to `Modify the configuration file`, but it doesn't say how. I just want to use the pretrained models which I've already downloaded, and provide my own images to process. If I just try to run the test script without modifying anything, I get:

```
$ python train.py -opt options/train/train_ESRGAN.yml
...
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/DIV2K/DIV2K800_sub.lmdb/meta_info.pkl'
```

How can we do this?

**Comment by ajparra** [comment]
Same question here

**Comment by anf6000** [comment]
Has anyone solved this? I have the same issue.

**Comment by Dejan1969** [comment]
How about using test.py instead of train.py

**Comment by AdvertiserM** [comment]
Has anyone figured this out yet?

**Comment by xinntao** [comment]
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
