### ISSUE TITLE
Error while trying to train ESRGAN

### ISSUE THREAD

**Issue by ienko** [open-mmlab/mmsr#17]
After running 'python train.py -opt options/train/train_ESRGAN.yml' with my own images, lmdb and yml configured accordingly, I keep getting this error:

19-10-08 08:00:18.801 - INFO: Loading model for G [../experiments/pretrained_models/RRDB_PSNR_x4.pth] ...
19-10-08 08:00:18.956 - INFO: Model [SRGANModel] is created.
19-10-08 08:00:18.956 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 149, in main
    for _, train_data in enumerate(train_loader):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 128 and 0 in dimension 3 at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/TH/generic/THTensor.cpp:711

Any help is very much appreciated.

**Comment by PSZehnder** [comment]
I am also running into this issue. Any help from the devs or people who have successfully trained on their own data sets would be much appreciated!

**Comment by PSZehnder** [comment]
@ienko I have found a solution. The issue was in LQGT_dataset.py in the random crop step. I rewrote the random crop algorithm like this:

`# random crop rewritten because their algo is fking broken >:(
            gt_h = random.randint(0, max(0, gH - GT_size))
            gt_w = random.randint(0, max(0, gW - GT_size))
            img_GT = img_GT[gt_h:gt_h + GT_size, gt_w:gt_w + GT_size, :]

            LQ_size = GT_size // scale
            lq_h = gt_h // scale
            lq_w = gt_w // scale
            img_LQ = img_LQ[lq_h:lq_h + LQ_size, lq_w:lq_w + LQ_size, :]
`

and that fixed the error

**Comment by ienko** [comment]
@PSZehnder great, thanks a lot. 

I also managed to solve it in a similar way, with writing another code for preprocessing the dataset I had (needed 4:3 with specific resolutions).  
       ```
        imgScale = H/height
        newX, newY = oriimg.shape[1]*imgScale, oriimg.shape[0]*imgScale
        newimg = cv2.resize(oriimg, (int(newX), int(H)))

        newWidth = int(W)
        newHeight = int(H)
        xBegin = (int(newX) - int(newWidth))/2
        xEnd = int(xBegin) + int(newWidth)
        cropped = newimg[0:1920, int(xBegin):int(xEnd)]
```
For some reason, it still doesn't work for all the batch sizes, but guess that's implied by network architecture.

**Comment by pratyushlohumi26** [comment]
The model arch is such that it requires: **(128,128,3)** as GT **(X)** and **(32,32,3)** as LR **(Y)**.

Keeping these two dimensions in mind, I was able to create my own dataset, then create it's corresponding lmdb files using the ./codes/data_scripts/create_lmdb.py and also validate the lmdb files created using the ./code/data_scrpits/test_dataloader.py file

Make sure that you have the correct paths present in the ./option/train/train_model.yaml file before starting the training. I hope if you adhere to these images dimensions you'll be able to fit a decent batch size depending upon your GPU memory available and start the training easily on the custom dataset.
