### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by mixtresh** [open-mmlab/mmsr#18]
19-10-11 18:15:50.311 - INFO: Data: Vid4 - ../content/drive/My Drive/app/mmsr/datasets/Vid4/BIx4/city/*
19-10-11 18:15:50.312 - INFO: Padding mode: new_info
19-10-11 18:15:50.312 - INFO: Model path: /content/drive/My Drive/app/mmsr/experiments/pretrained_models/EDVR_Vimeo90K_SR_L.pth
19-10-11 18:15:50.313 - INFO: Save images: True
19-10-11 18:15:50.313 - INFO: Flip test: False
19-10-11 18:15:52.915 - INFO: ################ Tidy Outputs ################
19-10-11 18:15:52.916 - INFO: ################ Final Results ################
19-10-11 18:15:52.916 - INFO: Data: Vid4 - ../content/drive/My Drive/app/mmsr/datasets/Vid4/BIx4/city/*
19-10-11 18:15:52.916 - INFO: Padding mode: new_info
19-10-11 18:15:52.916 - INFO: Model path: /content/drive/My Drive/app/mmsr/experiments/pretrained_models/EDVR_Vimeo90K_SR_L.pth
19-10-11 18:15:52.917 - INFO: Save images: True
19-10-11 18:15:52.917 - INFO: Flip test: False
Traceback (most recent call last):
  File "codes/test_Vid4_REDS4_with_GT.py", line 208, in <module>
    main()
  File "codes/test_Vid4_REDS4_with_GT.py", line 202, in main
    sum(avg_psnr_l) / len(avg_psnr_l), len(subfolder_l),
ZeroDivisionError: division by zero

**Comment by m732367606** [comment]
Please modify this line https://github.com/open-mmlab/mmsr/blob/dfdaaef492107f448ea49b9edebcb4f81e7893e8/codes/utils/util.py#L313
to
`elapsed = time.time() - self.start_time + 1e-8`
to avoid division by zero.
Hope this can help you!

**Comment by mixtresh** [comment]
thanks, but it not help

**Comment by Bueryoung** [comment]
"elapsed = time.time() - self.start_time + 1e-8"
This does not work

**Comment by xinntao** [comment]
Check your `avg_psnr_l`

It seems that no image is evaluated~
