### ISSUE TITLE
about GradientPenaltyLoss

### ISSUE THREAD

**Issue by suke27** [open-mmlab/mmsr#2]
Hello, I found you add GradientPenaltyLoss loss function in your loss.py, i try to use similar gradient of image as loss function, but seems it is not used, doesn't it work in SR training?

**Comment by xinntao** [comment]
The GradientPanaltyLoss is used for WGAN. We have conducted some preliminary experiments with WGAN but did not found improvements. So we do not use the GradientPenaltyLoss currently.
