### ISSUE TITLE
Actually assumed input range is [0, 1]?

### ISSUE THREAD

**Issue by S-aiueo32** [open-mmlab/mmsr#22]
In your MSRGAN model, it seems the output is not normalized to [0, 1].
This will not affect the output quality so much if the output passes post-processes, however, it is not valid as the input for VGG networks as you said [here](https://github.com/open-mmlab/mmsr/blob/master/codes/models/archs/discriminator_vgg_arch.py#L84):
```
# Assume input range is [0, 1]
```

If I missed the normalization processes, please point it out.

**Comment by xinntao** [comment]
The model will be trained to output images in [0, 1]
