### ISSUE TITLE
May be a bug

### ISSUE THREAD

**Issue by cctgem** [open-mmlab/mmsr#26]
In class REDSDataset, it need to update the key of  GT when border_mode is false and the center_frame_idx outside the range (0, 99), but name_a from key GT keeps constant all the time.

**Comment by Andyato** [comment]
what's the 'Bic' mean?

**Comment by xinntao** [comment]
Yes, it has fixed. 

BTW,
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
