### ISSUE TITLE
ERROR when run deform_conv.py

### ISSUE THREAD

**Issue by moomight** [open-mmlab/mmsr#27]
`
Traceback (most recent call last):
  File "deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from '__main__' (deform_conv.py)
`

Any help is appreciated !!

**Comment by mumuyanyan** [comment]
I have the same problem as you?
Have you dealt with the problem?

**Comment by vegetable09** [comment]
there is only cpp source file in codes/models/arch/dcn/src/deform_conv_cuda.cpp,  it seems that we should run cmd `python setup.py install` in codes/models/arch/dcn/ first to get a runnable deform_conv_cuda.py
