### ISSUE TITLE
Extending the model toolbox to other big algorithms

### ISSUE THREAD

**Issue by DonaldTsang** [open-mmlab/mmsr#33]
These are all repos with at least 300 stars, maybe there are some credibility with these repos, and if so, is it possible to implement them and add them to the toolkit?

Here are benchmarks done by somebody else:
- https://github.com/xiaomi-automl/FALSR
- https://github.com/huangzehao/Super-Resolution.Benckmark
- https://github.com/jbhuang0604/SelfExSR
- https://github.com/thstkdgus35/EDSR-PyTorch
- https://github.com/yulunzhang/RCAN
- https://github.com/limbee/NTIRE2017
- https://github.com/yulunzhang/RDN
- https://github.com/Paper99/SRFBN_CVPR19

Here are collections/toolkit collections:
- https://github.com/icpm/super-resolution
- https://github.com/krasserm/super-resolution
- https://github.com/titu1994/Image-Super-Resolution

And here is a list of models:
- https://github.com/ChaofWang/Awesome-Super-Resolution
- https://github.com/YapengTian/Single-Image-Super-Resolution
- https://github.com/LoSealL/VideoSuperResolution

Reasoning behind this test: Adoption of SR in drawings https://github.com/nagadomi/waifu2x/issues/251

**Comment by DonaldTsang** [comment]
Here is a list of models that have high hitrates
- (Unnamed) https://github.com/alexjc/neural-enhance
- SREZ https://github.com/david-gpu/srez
- (Unnamed) https://github.com/atriumlts/subpixel
- SinGAN https://github.com/tamarott/SinGAN
- RDN https://idealo.github.io/image-super-resolution/
- EDSR https://github.com/thstkdgus35/EDSR-PyTorch
- ProSR https://github.com/fperazzi/proSR
- DnCNN https://github.com/cszn/DnCNN
- RCAN https://github.com/yulunzhang/RCAN
- DPSR https://github.com/cszn/DPSR
- DCSCN https://github.com/jiny2001/dcscn-super-resolution
- (Unnamed) https://github.com/limbee/NTIRE2017
- WDSR https://github.com/JiahuiYu/wdsr_ntire2018
- RAISR https://github.com/movehand/raisr
- SRCNN https://github.com/tegg89/SRCNN-Tensorflow
- LapSRN https://github.com/phoenix104104/LapSRN
- SRCNN https://github.com/DeNA/SRCNNKit
- DBPN https://github.com/alterzero/DBPN-Pytorch
- RDN https://github.com/yulunzhang/RDN
- SRFBN https://github.com/Paper99/SRFBN_CVPR19

**Comment by xinntao** [comment]
Thanks for suggestions!

Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
