### ISSUE TITLE
[bug report] Why calculate ssim for three times? 

### ISSUE THREAD

**Issue by JingyunLiang** [open-mmlab/mmsr#35]
In the function `calculate_ssim`, it calculates ssim(img1, img2) for three times. Did you try to calculate ssim for different channels? If so, it's a bug.
```

def calculate_ssim(img1, img2):
    '''calculate SSIM
    the same outputs as MATLAB's
    img1, img2: [0, 255]
    '''
    if not img1.shape == img2.shape:
        raise ValueError('Input images must have the same dimensions.')
    if img1.ndim == 2:
        return ssim(img1, img2)
    elif img1.ndim == 3:
        if img1.shape[2] == 3:
            ssims = []
            for i in range(3):
                ssims.append(ssim(img1, img2))
            return np.array(ssims).mean()
        elif img1.shape[2] == 1:
            return ssim(np.squeeze(img1), np.squeeze(img2))
    else:
        raise ValueError('Wrong input image dimensions.')
```
https://github.com/open-mmlab/mmsr/blob/a73b318f0f07feb6505ef5cb1abf0db33e33807a/codes/utils/util.py#L272

**Comment by Feynman1999** [comment]
waiting for the answer too...

**Comment by csmiler** [comment]
According to
https://github.com/open-mmlab/mmsr/blob/e3ee7b527fed790b3943faddaa32f4d7ecf01064/codes/metrics/calculate_PSNR_SSIM.m#L57-L66
I think it should be
```ssims.append(ssim(img1[...,i], img2[...,i]))```
compute the ssim for each channel and then take the mean

**Comment by xinntao** [comment]
This is a bug. Thanks~

BTW,
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
