### ISSUE TITLE
the loss fluctuates and doesn't down

### ISSUE THREAD

**Issue by mnoiy** [open-mmlab/mmsr#36]
hello,I train the model use MSRResNet without using gan,but the loss only fluctuates but doesn't down ,
while  the psnr increases
The lr_scheme that I use is CosineAnnealingLR_Restart 
the tensorboard out :
when 
![image](https://user-images.githubusercontent.com/26063228/70799697-550f3e00-1de5-11ea-878d-9e6f5c760acd.png)

![image](https://user-images.githubusercontent.com/26063228/70799658-37da6f80-1de5-11ea-98b0-447ef419be94.png)
when
![image](https://user-images.githubusercontent.com/26063228/70799721-61939680-1de5-11ea-93d4-fe56ed975a92.png)

![image](https://user-images.githubusercontent.com/26063228/70799732-69ebd180-1de5-11ea-9543-3ef178291222.png)

**Comment by cleverMRtian** [comment]
I also encountered this situation.I will really appreciate it, if anyone can answer this question.

**Comment by xinntao** [comment]
Maybe you can find the explaination here~

https://github.com/xinntao/EDVR/wiki/FAQs

BTW,
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
