### ISSUE TITLE
How to test without GT?

### ISSUE THREAD

**Issue by SoulCoderCN** [open-mmlab/mmsr#4]
The test image and the corresponding GT must be defined in test_ESRGAN.yml. If I just want to test a random image, this image has no GT, what should I do?

**Comment by XiaotianM** [comment]
you can get answer from https://github.com/xinntao/ESRGAN

**Comment by SoulCoderCN** [comment]
No GT can get the predicted result, but the code will automatically compare the predicted result with the GT, so the code will output an error. You can use the following code to customize the GT, the code can run normally：
# raw image (80, 40, 3)
import cv2
import numpy as np
gt = np.ones(640, 320, 3)
cv2,imwrite("gt.jpg", gt)

**Comment by xinntao** [comment]
We have provided testing without GT. 
An example config file is in https://github.com/open-mmlab/mmsr/blob/master/codes/options/test/test_ESRGAN_woGT.yml

In that config yml file, we use `LQ` mode dataset and only need to specify the LQ path.
