### ISSUE TITLE
Please make training less sensitive to faulty PNGs

### ISSUE THREAD

**Issue by TomArrow** [open-mmlab/mmsr#42]
When I export an image sequence from VirtualDub, sometimes PNGs will have little errors. They still work, but CV2 cannot read them. For example, "libpng error: IDAT: invalid stored block lengths" and similar errors occur. 

With hundreds of thousands of files, it is hard to predict or test. pngcheck for example cannot detect some of these errors and any other software can read them well.

BasicSR will completely stop when such an error happens.

The error happens inside the util.read_img function:
```
if env is None:  # img
        img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    else:
        img = _read_img_lmdb(env, path, size)
    img = img.astype(np.float32) / 255.
```

imread throws the error, and astype then throws the Exception that crashes the script.

I've solved it by putting the call to util.read_img inside a try except clause inside `__getitem__` and having it return the last image instead:
```
try: 
    img_GT = util.read_img(self.GT_env, GT_path, resolution)
except:
    return self.__getitem__(index-1)
```

(the same for img_LQ as well)

But I am a Python noob and I think that events like this should get logged and I don't know how to log them. Can you implement something like this including logging so that one can read the log to see what image was faulty?

**Comment by xinntao** [comment]
Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
