### ISSUE TITLE
Is it possible to realise a new dataloader without lmdb in your framework?

### ISSUE THREAD

**Issue by Rainyfish** [open-mmlab/mmsr#44]
Hi, 
    Thank you for providing a powerful tool. But sometime the input data maybe is not pictures, Is it possible to realise a new dataloader without lmdb in your framework and which part of your framework need to be changed expect dataload?

**Comment by xinntao** [comment]
Yes, it supports.
BTW,
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
