### ISSUE TITLE
Test images with CUDA ERROR: Out of memory

### ISSUE THREAD

**Issue by cydiachen** [open-mmlab/mmsr#45]
Dear Xintao:
I am now using your mmsr module to train my own model. Your code works excellent during training. But when it comes to testing, Your algorithm displayed out of memory error when processing images. I assume it is because the size of output images caused this error. I am wondering whether to solve this problem.

**Comment by xinntao** [comment]
You may have too large input images during testing.
If so, try to crop the input image to several sub-images, process each and finally stitch them.

**Comment by ryul99** [comment]
I uploaded my script for cropping to sub-images and stitch sub-images.
I hope this could help you.
https://gist.github.com/ryul99/a192310cf2cd3ce94f83b928d44a141f
