### ISSUE TITLE
Question about create_lmdb. py

### ISSUE THREAD

**Issue by yangyingni** [open-mmlab/mmsr#46]
Hello,thank you for your work first.I have a question about the size of lr pictures.I want to ask whether i can use 128*128 hr pictures and 8x downsampled lr pictures(16*16),i changed all scale_ratio correctly and when i ran create_lmdb.py,it shows lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached  I can get ../dataset/DIK2K/DIV2K800_sub_bicLRx8.lmdb and ../dataset/DIK2K/DIV2K800_sub.lmdb,but no meta_info.pkl under DIV2K800_sub_bicLRx8.lmdb.Can you tell me why?Thank you.

When i run python create_lmdb.py,it shows
Traceback (most recent call last):
File "create_lmdb.py", line 411, in 
main()
File "create_lmdb.py", line 44, in main
general_image_folder(opt)
File "create_lmdb.py", line 120, in general_image_folder
txn.put(key_byte, data)
lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached.

**Comment by xinntao** [comment]
As the error indicates, it is because the lmdb container has limited size.
you can enlarge the assigned space by change `map_size` in 
`env = lmdb.open(lmdb_save_path, map_size=data_size * 10)`

 
But the create_lmdb.py will automatically assign a 10x larger space=-=

**Comment by yangyingni** [comment]
Thank you very much,I have solved this question,I tried this way earlier,but it failed. Later I turned map_size into solid number,and it successed.&nbsp;



---Original---
