### ISSUE TITLE
Why we do not need to use DistributedDataParallel for netF?

### ISSUE THREAD

**Issue by rakhimovv** [open-mmlab/mmsr#47]
Thanks for the great project. Looking through code, I noticed that in SRGAN_model.py there are such lines:
```
if opt['dist']:
    pass  # do not need to use DistributedDataParallel for netF
else:
    self.netF = DataParallel(self.netF)
```
can you please provide motivation of not wrapping netF with DistributedDataParallel

**Comment by xinntao** [comment]
Because there is no need to update netF during training. 
If we use DistributedDataParallel for netF and we do not update netF, then errors will be raised.

**Comment by rakhimovv** [comment]
Thanks for the answer!
