### ISSUE TITLE
Extra Gradient Detach?

### ISSUE THREAD

**Issue by Queuecumber** [open-mmlab/mmsr#53]
In 

https://github.com/open-mmlab/mmsr/blob/master/codes/models/SRGAN_model.py#L189

Why do you detach to the result of `netD` on fake image? Won't that prevent gradient from fake images from backproping to the discriminator?

**Comment by Queuecumber** [comment]
OK I guess you rerun the discriminator on 193 but is it really necessary to detach at line 189?

**Comment by xinntao** [comment]
In the L189, we only want to train netD with real images.

According to the official codes, https://github.com/AlexiaJM/RelativisticGAN, it does not use detach. 
The two implementations (comment and uncomment ones) does not influence the final results much. I think the current implementation may be more suitable. We will revisit it and update it ~
