### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1912,1912,3) (112,112,3)

### ISSUE THREAD

**Issue by vegetable09** [open-mmlab/mmsr#57]
20-03-04 20:15:37.214 - INFO: [epoch: 4, iter: 4,900, lr:(1.000e-04,)] l_g_pix: 3.7640e-04 l_g_fea: 9.9916e-01 l_g_gan: 2.9927e-02 l_d_real: 1.9228e-03 l_d_fake: 1.5228e-03 D_real: 7.3041e+01 D_fake: 6.7059e+01
20-03-04 20:17:49.691 - INFO: [epoch: 4, iter: 5,000, lr:(1.000e-04,)] l_g_pix: 3.4310e-04 l_g_fea: 9.8867e-01 l_g_gan: 1.9802e-02 l_d_real: 2.2165e-02 l_d_fake: 1.5732e-02 D_real: 1.2171e+02 D_fake: 1.1779e+02
[ ] 0/4144, elapsed: 0s, ETA:
Start...
Traceback (most recent call last):
File "train.py", line 310, in <module>
mse = np.mean((img1 - img2)**2)
main()
File "train.py", line 202, in main
avg_psnr += util.calculate_psnr(sr_img, gt_img)
File "/workdir/mmsr/codes/utils/util.py", line 230, in calculate_psnr
ValueError: operands could not be broadcast together with shapes (1912,1912,3) (112,112,3)

**Comment by vegetable09** [comment]
I was running train.py and using pretrained ESRGAN model，all parameters is same as the master branch. All things work well until this error. I search this problem on google and they said this is because different padding strategy in main road and the secondary road of Resnet. But I have no idea where the 1912 and 112 come from, anyone can help?

**Comment by sandeepjangir07** [comment]
which scale where you training ?

**Comment by vegetable09** [comment]
> which scale where you training ?

x4

**Comment by vegetable09** [comment]
find reason, in train.yml, I just used wrong LR and GT path, after swap the path, it works well
