### ISSUE TITLE
 Pretrained model D

### ISSUE THREAD

**Issue by TheLostIn** [open-mmlab/mmsr#62]
Hi,could you please provide pretrained model D?

**Comment by Desera** [comment]
I think there is no pretrained model D

**Comment by xinntao** [comment]
We will release pre-trained models later.

BTW,

Thanks for using MMSR. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
