### ISSUE TITLE
why using `var_ref` in 'SRGAN_model.py'

### ISSUE THREAD

**Issue by ShangyinGao** [open-mmlab/mmsr#64]
it seems the `var_ref` in line 175 of 'SRGAN_model.py' contains the same image as `var_H`, at least when ESRGAN is used.
Is there any particular reason, why `var_ref` was used not `var_H`?

**Comment by xinntao** [comment]
We have tried to use other reference images (other than the HR image) to train SRGAN. 

var_ref is not used any more. We will remove it~
