### ISSUE TITLE
Can't get past installation process, what am I doing wrong?

### ISSUE THREAD

**Issue by AdvertiserM** [open-mmlab/mmsr#65]
I'm new to this program so I just enter it into the command prompt but get this error 

C:\users\Scott>cd cd ./codes/models/archs/dcn
The system cannot find the path specified. 

I tried this in a command prompt, anaconda and git bash all give there own errors

**Comment by Dejan1969** [comment]
You take Instructions too literally, if you are in c:\user\scott question is where is your mmsr installation?
Try cd mmsr, cd codes, cd models, cd archs, cd dcn, one after another
Once your prompt looks like c:\user\scott\mmsr\codes\models\archs\dcn, you can compile dcn with
python setup.py develop

**Comment by SreeHarshaNelaturu** [comment]
I reckon the double cd is what is causing the issue.
Try
`cd mmsr/codes/models/archs/dcn
'
in C:\users\Scott -- this should work.
