### ISSUE TITLE
ImportError: Failed to import DCNv2 module

### ISSUE THREAD

**Issue by sirwes** [open-mmlab/mmsr#69]
I followed the setup instructions found on the page, but when I download the pretrained model and run 
'python test.py -opt options/test/test_ESRGAN.yml
'
I get the following error:

` ImportError: Failed to import DCNv2 module.`

I guess it's because it won't import 

` from models.archs.dcn.deform_conv import ModulatedDeformConvPack as DCN
`
But why?

torch: 1.2.0
gcc: 5.4.0
cuda 10.1
torchvision: 0.4.0a0+6b959ee

**Comment by ryul99** [comment]
In my case, That happens when DCN is not built perfectly. You should use gcc 4.9 or higher.

**Comment by sirwes** [comment]
I upgraded gcc to 5.4.0 and got this error when running the command
>python setup.py develop
>gcc: error: src/deform_conv_cuda.cpp: No such file or directory

**Comment by sirwes** [comment]
Found the problem. In the setup.py, line 21 it reads this:

`                      sources=['src/deform_conv_cuda.cpp', 'src/deform_conv_cuda_kernel.cu'])
`
It was looking for <cuda_home path>/src/deform_conv_cuda.cpp which of course wasn't there. It was here:
mmsr-master/codes/models/archs/dcn/src/deform_conv_cuda.cpp 

By updating that line with the correct path, everything installed correctly.

And now running the command

`python test.py -opt options/test/test_ESRGAN.yml`
the error is resolved, and instead replaced with a operand broadcast error on line 230 in codes/utils/util.py

That may just be the custom images I pulled in though
