### ISSUE TITLE
Error when run python setup.py develop[pytorch1.0]

### ISSUE THREAD

**Issue by zhhezhhe** [open-mmlab/mmsr#7]
```
src/deform_conv_cuda_kernel.cu(258): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

src/deform_conv_cuda_kernel.cu(352): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

src/deform_conv_cuda_kernel.cu(450): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

src/deform_conv_cuda_kernel.cu(780): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

src/deform_conv_cuda_kernel.cu(812): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

src/deform_conv_cuda_kernel.cu(845): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

6 errors detected in the compilation of "/tmp/tmpxft_000126d0_00000000-6_deform_conv_cuda_kernel.cpp1.ii".
error: command '/home/work/cuda-9.0/bin/nvcc' failed with exit status 1
```

**Comment by OreOooRanJie** [comment]
I encounter the same problem,and my env is :

- pytorch 1.0

- cuda 9.0

- gcc 5.4.6

- ubuntu 16.04

**Comment by xinntao** [comment]
Do you have several cuda environments? 
Try to set CUDA_HOME before the compilation.

**Comment by OreOooRanJie** [comment]
> Do you have several cuda environments?
> Try to set CUDA_HOME before the compilation.

thank you for your suggestion,I have only one cuda 9.0.
And then I tried what you said but failed.

**Comment by xinntao** [comment]
It seems that this error is from the incorrect cuda version. 

1. modify the following paths before compiling:
`CUDA_HOME=/usr/local/cuda-10.0 CUDNN_INCLUDE_DIR=/usr/local/cuda-10.0/include CUDNN_LIB_DIR=/usr/local/cuda-10.0/lib64 python setup.py build develop`
2. related issues, but it seems this is not your case: https://github.com/open-mmlab/mmdetection/issues/1174
3. may try to resinstall pytorch or use a higher cuda version.

**Comment by zhhezhhe** [comment]
> It seems that this error is from the incorrect cuda version.
> 
> 1. modify the following paths before compiling:
>    `CUDA_HOME=/usr/local/cuda-10.0 CUDNN_INCLUDE_DIR=/usr/local/cuda-10.0/include CUDNN_LIB_DIR=/usr/local/cuda-10.0/lib64 python setup.py build develop`
> 2. related issues, but it seems this is not your case: [open-mmlab/mmdetection#1174](https://github.com/open-mmlab/mmdetection/issues/1174)
> 3. may try to resinstall pytorch or use a higher cuda version.

Thank you for your answer. But I have no sudo. And my early code is based CUDA-9.0. I want to run your code together with mine. Thanks anyway.

**Comment by yhjo09** [comment]
I also failed to complie on Pytorch 1.0, but Pytorch 1.1 can compile the code with CUDA 10.0.

**Comment by xinntao** [comment]
@yhjo09 Thanks
It seems the complication of dcn package needs pytorch1.1.
We have updated the readme file.

**Comment by PyxAI** [comment]
I had pytorch 1.1.0 and upgrading to 1.2 solved the issue
