### ISSUE TITLE
Float Divide by zero issue in util.py

### ISSUE THREAD

**Issue by superaoe** [open-mmlab/mmsr#75]
codes\utils\util.py

Got this while creating an LMDB, line 314 in util.py division by zero error. Pretty sure its because it runs that line immediately and obviously 0 time has passed.
    
fps = self.completed / elapsed

I "fixed" it by changing it to 

fps = self.completed / (elapsed + 0.01)

I'm not sure what the appropriate etiquette is here but I'm sure someone that knows better than me can write a more elegant fix.  But it works. Its just for the progress bar while creating the database so its really not a big deal.

**Comment by xinntao** [comment]
Thanks for your suggestion. 
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
