### ISSUE TITLE
 Out of memory - script killed

### ISSUE THREAD

**Issue by sebmasterid** [open-mmlab/mmsr#80]
I want to upscale a video HD in 4K.

I exported the video to a png sequence and create sub-images to avoid  CUDA ERROR: Out of memory (V100 with 16 Go).

But with 7000 png in a folders, the script is killed at

imgs_LQ = data_util.read_img_seq(test_dataset_folder)

Any idea to avoid it ?

**Comment by sebmasterid** [comment]
With only 100 images, it works...

**Comment by Atheryl** [comment]
How did you export to PNG and recompile the video in an effective way?
