### ISSUE TITLE
vgg_feature mean value for (-1,1) input

### ISSUE THREAD

**Issue by AloneGu** [open-mmlab/mmsr#87]
https://github.com/open-mmlab/mmsr/blob/e3ee7b527fed790b3943faddaa32f4d7ecf01064/codes/models/archs/discriminator_vgg_arch.py#L73

I guess it should be 
```
 [0.485*2 - 1, 0.456*2 - 1, 0.406*2 - 1] if input in range [-1, 1]
```

suppose x in range (-1,1) , convert and preprocess:

```
feat = [(x+1)/2 - mean]/std = [x-(2*mean-1)]/(2*std)
```

**Comment by xinntao** [comment]
Yes，you are right！
We will update it.

BTW,
We will upgrade MMSR to MMEditing (in the same repo), which consists of SR, inpainting, matting and generation tasks. 
And MMSR will be deprecated and no longer exist.
Your suggestions will be updated in MMEditing.
