### ISSUE TITLE
about the datasets

### ISSUE THREAD

**Issue by LINSEVENQI** [open-mmlab/mmsr#88]
Hello, are you willing to provide the video address of the Sampled Clips from Viemo-90K displayed on http://data.csail.mit.edu/tofu/dataset.html? Or how can I download the videos shown in http:/ /data.csail.mit.edu/tofu/dataset.html?

**Comment by xinntao** [comment]
I do not know the id of the sample clips in http://data.csail.mit.edu/tofu/dataset.html. 

You may ask the authors of the Viemo-90K dataset.
