### ISSUE TITLE
Training and generating with or without LMDB in a general images folder

### ISSUE THREAD

**Issue by chlorophyll-zz** [open-mmlab/mmsr#9]
I love to experimenting with neural networks and machine learning. 
Thank you for this great tool. 

So, i read that i could put pictures in a general image folder.
Unfortunately the images folder location is not clear for me.

I got my to-enhace-Images from a movie in mmsr/images/image-xxxx.jpg
I downloaded the movie with youtube-dl and converted to still frames with ffmpeg.

`python train.py -opt options/train/train_SRResNet.yml`

> export CUDA_VISIBLE_DEVICES=0
> Disabled distributed training.
> 19-09-05 11:13:52.512 - INFO:   name: 001_MSRResNetx4_scratch_DIV2K
>   use_tb_logger: True
>   model: sr
>   distortion: sr
>   scale: 4
>   gpu_ids: [0]
>   datasets:[
>     train:[
>       name: DIV2K
>       mode: LQGT
>       dataroot_GT: ../datasets/DIV2K/DIV2K800_sub.lmdb
>       dataroot_LQ: ../datasets/DIV2K/DIV2K800_sub_bicLRx4.lmdb
>       use_shuffle: True
>       n_workers: 6
>       batch_size: 16
>       GT_size: 128
>       use_flip: True
>       use_rot: True
>       color: RGB
>       phase: train
>       scale: 4
>       data_type: lmdb
>     ]
>     val:[
>       name: val_set5
>       mode: LQGT
>       dataroot_GT: ../datasets/val_set5/Set5
>       dataroot_LQ: ../datasets/val_set5/Set5_bicLRx4
>       phase: val
>       scale: 4
>       data_type: img
>     ]
>   ]
>   network_G:[
>     which_model_G: MSRResNet
>     in_nc: 3
>     out_nc: 3
>     nf: 64
>     nb: 16
>     upscale: 4
>     scale: 4
>   ]
>   path:[
>     pretrain_model_G: None
>     strict_load: True
>     resume_state: None
>     root: /content/mmsr
>     experiments_root: /content/mmsr/experiments/001_MSRResNetx4_scratch_DIV2K
>     models: /content/mmsr/experiments/001_MSRResNetx4_scratch_DIV2K/models
>     training_state: /content/mmsr/experiments/001_MSRResNetx4_scratch_DIV2K/training_state
>     log: /content/mmsr/experiments/001_MSRResNetx4_scratch_DIV2K
>     val_images: /content/mmsr/experiments/001_MSRResNetx4_scratch_DIV2K/val_images
>   ]
>   train:[
>     lr_G: 0.0002
>     lr_scheme: CosineAnnealingLR_Restart
>     beta1: 0.9
>     beta2: 0.99
>     niter: 1000000
>     warmup_iter: -1
>     T_period: [250000, 250000, 250000, 250000]
>     restarts: [250000, 500000, 750000]
>     restart_weights: [1, 1, 1]
>     eta_min: 1e-07
>     pixel_criterion: l1
>     pixel_weight: 1.0
>     manual_seed: 10
>     val_freq: 5000.0
>   ]
>   logger:[
>     print_freq: 100
>     save_checkpoint_freq: 5000.0
>   ]
>   is_train: True
>   dist: False
> 
> 19-09-05 11:13:54.299 - INFO: Random seed: 10
> WARNING: Logging before flag parsing goes to stderr.
> I0905 11:13:54.299421 140545874597760 train.py:94] Random seed: 10
> Traceback (most recent call last):
>   File "train.py", line 310, in <module>
>     main()
>   File "train.py", line 104, in main
>     train_set = create_dataset(dataset_opt)
>   File "/content/mmsr/codes/data/__init__.py", line 44, in create_dataset
>     dataset = D(dataset_opt)
>   File "/content/mmsr/codes/data/LQGT_dataset.py", line 24, in __init__
>     self.paths_GT, self.sizes_GT = util.get_image_paths(self.data_type, opt['dataroot_GT'])
>   File "/content/mmsr/codes/data/util.py", line 51, in get_image_paths
>     paths, sizes = _get_paths_from_lmdb(dataroot)
>   File "/content/mmsr/codes/data/util.py", line 37, in _get_paths_from_lmdb
>     meta_info = pickle.load(open(os.path.join(dataroot, 'meta_info.pkl'), 'rb'))
> FileNotFoundError: [Errno 2] No such file or directory: '../datasets/DIV2K/DIV2K800_sub.lmdb/meta_info.pkl'

So i create a lmdb, which would not actually be necessary form your description on Datasets, 
the Script data_scipts/create_lmdb.py looks in DIV2K800_sub and fails too. 

`python data_scipts/create_lmdb.py
`
> Reading image path list ...
> Traceback (most recent call last):
>   File "data_scripts/create_lmdb.py", line 411, in <module>
>     main()
>   File "data_scripts/create_lmdb.py", line 39, in main
>     general_image_folder(opt)
>   File "data_scripts/create_lmdb.py", line 102, in general_image_folder
>     data_size_per_img = cv2.imread(all_img_list[0], cv2.IMREAD_UNCHANGED).nbytes
> IndexError: list index out of range

**Comment by xinntao** [comment]
You can use the image folder.
But from your provided log, you did not modify the `dataroot_GT` and `dataroot_LQ`, which should be the path to your GT and LR image folders.

**Comment by chlorophyll-zz** [comment]
> You can use the image folder.
> But from your provided log, you did not modify the `dataroot_GT` and `dataroot_LQ`, which should be the path to your GT and LR image folders.

Correct. I realized that i wanted to test on a real world video. 
So i tried to create a LMDB for the Images. The script failed. 
I think the variable general_image_folder is not defined, 
or should i pass the image folder as an argument to the create_lmdb script?

`python data_scipts/create_lmdb.py`
> 
> Reading image path list ...
> Traceback (most recent call last):
> File "data_scripts/create_lmdb.py", line 411, in
> main()
> File "data_scripts/create_lmdb.py", line 39, in main
> general_image_folder(opt)
> File "data_scripts/create_lmdb.py", line 102, in general_image_folder
> data_size_per_img = cv2.imread(all_img_list[0], cv2.IMREAD_UNCHANGED).nbytes
> IndexError: list index out of range

**Comment by anf6000** [comment]
Did you manage to figure it out? I am having the same issue...

**Comment by chlorophyll-zz** [comment]
nope, unfortunately not
